---
sidebar_position: 2
---
import { PackageBadgeGroup } from '@site/src/components/PackageBadgeGroup';
import { PackageInstallBlock } from '@site/src/components/PackageInstallBlock';

# CustomError

> Error factory creation

<PackageBadgeGroup apiHref="/api/error" />

## Motivation

Extending `globalThis.Error` have multiple drawbacks :

- Matching on errors relies on `instanceof` which have some limitations (ex: `iframe`)
- Can be verbose even for adding just one property

The `@w5s/error` package helps creating type safe errors :

- Easy declaration using `CustomError.define`
- Type safe matching on `name`
- Discourage matching using `instanceof`

## Usage

```ts
import { CustomError } from '@w5s/error';

interface SomeError
  extends CustomError<{
    name: 'SomeError';
    customProperty: string;
  }> {}
const SomeError = CustomError.define<SomeError>({ 
  errorName: 'SomeError',
  // (Optional) A default message can be set
  // errorMessage: 'This is a default message',
});

console.log(SomeError({
  message: 'This is a message',
  customProperty: 'custom',
  cause: new TypeError('This is the cause')
}));
// SomeError {
//   name: 'SomeError',
//   message: 'This is a message',
//   customProperty: 'custom',
//   cause: TypeError { message: 'This is the cause' }
// }
```

## Throwing errors

:::warning

### Use `throwError` (and `throw`) with caution

In general, **throwing errors is discouraged**, instead [Result](../core/result) should be used.

Nevertheless, errors can be thrown when :

- Program is in an impossible state and should be stopped (i.e. panic)
- An unexpected operation was done that was not caught during compile time

:::

`throwError` is equivalent to `throw` but as a function, it has the advantages :

- it can be used as an expression (ex: in ternary operator)
- it can be used as a parameter (ex: as a callback)

```ts
import { throwError } from '@w5s/error';

function assertNotNullable(value: unknown) {
  return value ?? throwError(new TypeError('Value must not be nullable'));
}
```

## Matching errors

The recommended way to match on errors created with `CustomError.define` is to use a `switch` / `case` on the error `name`

```ts
interface FooError
  extends CustomError<{
    name: 'FooError';
    fooProperty: boolean;
  }> {}
const FooError = CustomError.define<FooError>({ errorName: 'FooError' });

interface BarError
  extends CustomError<{
    name: 'BarError';
    barProperty: number;
  }> {}
const BarError = CustomError.define<BarError>({ errorName: 'BarError' });

function parse(): Result<string, FooError | BarError> {
  //...
}

function program() {
  const result = parse();
  if (Result.isError(result)) {
    switch (result.name) {
      case FooError.typeName: { 
        console.log('FooError:', error.fooProperty);
        break;
      }
      case BarError.typeName: { 
        console.log('BarError:', error.barProperty);
        break;
      }
      default: assertNever(result.name);
    }
  }
}

```

## Caused / Specializing error

`CustomError` can be used to create specific errors with a `cause` property that is useful to keep track of the chain of errors.

```ts
export interface CauseError
  extends CustomError<{
    name: 'CauseError';
  }> {}
export const CauseError = CustomError.define<CauseError>({ errorName: 'CauseError' });

try {
  // ...
} catch (error) {
  throw CauseError({
    message: 'This is a better error',
    cause: error,
  });
}
```

## Coding Guide

```ts
// ✓ Export an interface
// ✓ PascalCase
// ✓ Name + 'Error'
export interface {{SomeError}} extends CustomError<{
  name: '{{SomeError}}';// <- This is required
  // Add more properties
  // ...
}> {}
// ✓ Export const with same name as const
export const {{SomeError}} = CustomError.define<{{SomeError}}>({ 
  errorName: {{SomeError}}
});
```

## FAQ
